### PR TITLE
Outliers

### PR DESCRIPTION
**Pull request by tjma12**
Implements a simple version of a standard deviation cut on the range and h(t) BLRMS channels.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@tjma12, can you describe the logic in the new `remove_outliers` method? I'm trying to work out if there's a way to do the operation with array logic, rather than a `for` loop.

**Comment by duncanmmacleod** [comment]
Also, can you please post a before/after example of what this PR does.

**Comment by tjma12** [comment]
@duncanmmacleod For the quick and ugly first version I replaced any data point that was beyond the sigma threshold with the average of the points on either side of it. I wrote in two edge cases, if the bad point is the first point in the data set, it averages the two points in front of it, if it's the last point in the data set it averages the two points behind it. 

Before: https://ldas-jobs.ligo-wa.caltech.edu/~tjmassin/detchar/slow-correlations/removed-outliers/v2/outliers/
After a 2 sigma cut: https://ldas-jobs.ligo-wa.caltech.edu/~tjmassin/detchar/slow-correlations/removed-outliers/v2/removed_outliers_range_blrms/

The r-values go from an average of about 0.2 to an average of about 0.55 and the scaling on the plots works a bit better without big peaks pushing around the scaling.

**Comment by duncanmmacleod** [comment]
would it work just as well to simply ping the outliers to the 2-sigma value?

```python
mean_ = ts.mean()
threshold = N * ts.std()
ts[ts>mean_+threshold] = mean_ + threshold
ts[ts<mean_-threshold] = mean_ - threshold
```

**Comment by tjma12** [comment]
I don't think so, at least not reliably, it would probably require a lot of tuning to get the right sigma value. Here's an example with the mean and +/- 2 sigma lines outlined, replacing the peaks would still leave a bit of an outlier behind: https://ldas-jobs.ligo.caltech.edu/~thomas.massinger/detchar/smooth_range/RMS.png

**Pull request merged**
